



logging.level:
  root: INFO
  com.example.lab01.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR


server:
  port: 7070

spring:
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
    user: root
    password: "{cipher}AgCtSOHaxhXqY/BSbzNr0CjuAIJtoBXDIUQj3fNeCGE8GYQRGb3xrRdkQ6zkFLnMM5tXzGpdM5ELzZYaGawuuhLREe0PNSEnL39ndfXg689kJpcVaeEF5PsSUnx3iEl5KX2k7DsYfCJiYQXHK2vsAzVHPEUnr5YVv5vjtdyrGHM1kYbaNZJKee+xi1mPTqE91HJj032KGEeLN33nw7quWveX19qFk/uABz9lytEyCgxVzIlHnA2DMYkd68uXJV73hDFm9LpuiZ/L2YNDDrHQxEtfYa5Rs9iS/eZF+rFT7A8aCSd90uTrsFBxxG401LvFUC5RfcAfY9Ppjb7/onkREQZSs6LXvtuanmTtrWZwTsgsQfERKubtEeFVXnaWpTirHihsAaDzNHH5PneC82fcdLYn4cJfEQ3gm/9NT0EIZq+gGut/OsOiWByIoEEto1gPi4kacMRLevI5Xj5krrJwy1UAuak8f8Rgmz/y12BKo2c4ojBlT1L4/VNcXOzr9YmjLavBNXv3IDcPUbkAyKZTytMjvY+/91+AZo7oUav1te48xX4UpMtZIbgfbVDX4aZ7VvFgnseYYG1rqFH5Wa6jmKZ5RcigmWjKc/ErrMiJBRgiN72f0CrbuVIGY2GdWYLdtFo51r9OQErYOeOHtOztw6c+tZIsne+LesdOnDMk4qeXaUeuJlBsLOmi/5jX69PzdbYk8ynpvBn6UfsHmBuRkE0Y"
    locations: classpath:db/migration/lab01
    #schemas: dbo
    #flyway-schemas: flyway-schemas
    group: false

lab01:
  event:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  db01:
    url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
    username: lab01user
    password: lab01userpwd
    driverClassName: com.mysql.cj.jdbc.Driver

  features:
    crypto.key: 123456789012345678901234567890
    panicEnabled: false
    smtp1:
      host: gmail.com
      cc:
        - a@demo.com
        - b@demo.com
        - c@demo.com
      port: 8080
    smtp2:
      host: gmail.com
      cc:
        - a@demo.com
        - b@demo.com
        - c@demo.com
      port: 8080
    apis:
      - url: http://www.demo.com
        credential:
          user: admin
          password: password
        headers:
          heade1: value1
          heade2: value2
          heade4: value4
      - url: http://www.demo.com
        credential:
          user: admin
          password: password
        headers:
          heade1: value1
          heade2: value2
          heade4: value4
      - url: http://www.demo.com
        credential:
          user: admin
          password: password
        headers:
          heade1: value1
          heade2: value2
          heade4: value4
      - url: http://www.dem1o.com
        credential:
          user: admin
          password: passwor1d
        headers:
          heade1: value1
          heade2: value2
          heade4: value4

crypto.key: "keyvalue"
